"""add_square_payment_fields

Revision ID: 0f26238307fc
Revises: fbc983000596
Create Date: 2026-02-01 00:04:24.221490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f26238307fc'
down_revision = 'fbc983000596'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add SQUARE to PaymentType enum
    op.execute("ALTER TYPE paymenttype ADD VALUE IF NOT EXISTS 'SQUARE'")

    # Create PaymentStatus enum
    op.execute("CREATE TYPE paymentstatus AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')")

    # Add new columns to payment table
    op.add_column('payment', sa.Column('square_payment_id', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('payment', sa.Column('currency', sa.String(), nullable=True, server_default='USD'))
    op.add_column('payment', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=True))
    op.add_column('payment', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Create unique constraints
    op.create_unique_constraint('uq_payment_square_payment_id', 'payment', ['square_payment_id'])
    op.create_unique_constraint('uq_payment_idempotency_key', 'payment', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unique constraints
    op.drop_constraint('uq_payment_idempotency_key', 'payment', type_='unique')
    op.drop_constraint('uq_payment_square_payment_id', 'payment', type_='unique')

    # Drop columns
    op.drop_column('payment', 'created_at')
    op.drop_column('payment', 'receipt_url')
    op.drop_column('payment', 'status')
    op.drop_column('payment', 'currency')
    op.drop_column('payment', 'amount')
    op.drop_column('payment', 'idempotency_key')
    op.drop_column('payment', 'square_payment_id')

    # Drop PaymentStatus enum
    op.execute("DROP TYPE paymentstatus")

    # Note: Removing 'Square' from PaymentType enum requires recreating the enum
    # This is complex in PostgreSQL, so we skip it for the downgrade
    # ### end Alembic commands ###
