"""add pickup and type to orders

Revision ID: 15c77a444061
Revises: 95b7eb178808
Create Date: 2025-06-10 16:32:35.670948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c77a444061'
down_revision = '95b7eb178808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickupId', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('type', sa.Enum('DELIVERY', 'PICKUP', name='feetype'), nullable=True))
    op.alter_column('orders', 'addressId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'pickup_addresses', ['pickupId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'addressId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'type')
    op.drop_column('orders', 'pickupId')
    # ### end Alembic commands ###
