"""autogen: latest bill updates

Revision ID: 526d54f3b3dd
Revises: 61f8278c4e69
Create Date: 2025-05-20 23:26:13.265396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526d54f3b3dd'
down_revision = '61f8278c4e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('is_listed', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('inventory', sa.Column('is_available', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('order_items', sa.Column('updatedOrderitemsId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'order_items', ['updatedOrderitemsId'], ['id'])
    op.add_column('orders', sa.Column('bill_url', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('deliveryFee', sa.Float(), nullable=True, server_default=sa.text('5')))
    op.add_column('orders', sa.Column('tipAmount', sa.Float(), nullable=True, server_default=sa.text('0')))
    op.add_column('orders', sa.Column('orderTotalAmount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('taxAmount', sa.Float(), nullable=True, server_default=sa.text('0')))
    op.add_column('store', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('store', sa.Column('disabled', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('store', sa.Column('description', sa.String(), nullable=True))
    op.add_column('store', sa.Column('pincodes', sa.ARRAY(sa.String()), nullable=True, server_default=sa.text(
                "ARRAY['94102','94103','94107','94536','94016']"
            )))
    op.add_column('store', sa.Column('tnc', sa.String(), nullable=True))
    op.add_column('store', sa.Column('storeDeliveryFee', sa.Float(), nullable=True, server_default=sa.text('10')))
    op.add_column('store', sa.Column('taxPercentage', sa.Float(), nullable=True, server_default=sa.text('0')))
    op.add_column('users', sa.Column('secondary_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['cognitoId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'secondary_phone')
    op.drop_column('store', 'taxPercentage')
    op.drop_column('store', 'storeDeliveryFee')
    op.drop_column('store', 'tnc')
    op.drop_column('store', 'pincodes')
    op.drop_column('store', 'description')
    op.drop_column('store', 'disabled')
    op.drop_column('store', 'is_active')
    op.drop_column('orders', 'taxAmount')
    op.drop_column('orders', 'orderTotalAmount')
    op.drop_column('orders', 'tipAmount')
    op.drop_column('orders', 'deliveryFee')
    op.drop_column('orders', 'bill_url')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'updatedOrderitemsId')
    op.drop_column('inventory', 'is_available')
    op.drop_column('inventory', 'is_listed')
    # ### end Alembic commands ###
