"""Add new fields to Store, Inventory, User, and Order models

Revision ID: 61f8278c4e69
Revises: fb3f61bb854e
Create Date: 2025-05-16 21:44:08.322525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f8278c4e69'
down_revision = 'fb3f61bb854e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
