"""Make display_field non-nullable

Revision ID: 8877f427d4c7
Revises: 95b7eb178808
Create Date: 2025-06-07 23:18:10.098441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8877f427d4c7'
down_revision = '95b7eb178808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store', 'display_field',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store', 'display_field',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
