"""add section_headers and display_field

Revision ID: 95b7eb178808
Revises: fb3f61bb854e
Create Date: 2025-06-07 21:35:36.250447

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95b7eb178808"
down_revision = "fb3f61bb854e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("fee_rate", sa.Float(), nullable=False),
        sa.Column("fee_currency", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("DELIVERY", "PICKUP", name="feetype"), nullable=False
        ),
        sa.Column("limit", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pickup_addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "store_location_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.add_column("orders", sa.Column("display_code", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("custom_order", sa.String(), nullable=True))
    op.add_column(
        "store", sa.Column("section_headers", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("store", sa.Column("display_field", sa.String(), nullable=True))
    op.create_unique_constraint("uq_store_display_field", "store", ["display_field"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_store_display_field", "store", type_="unique")
    op.drop_column("store", "display_field")
    op.drop_column("store", "section_headers")
    op.drop_column("orders", "custom_order")
    op.drop_column("orders", "display_code")
    op.drop_table("store_location_codes")
    op.drop_table("pickup_addresses")
    op.drop_table("fees")
    op.execute("DROP TYPE IF EXISTS feetype")
    # ### end Alembic commands ###
