"""add_payment_onboarding_table

Revision ID: e9f963a9f687
Revises: 3ffe09b7cada
Create Date: 2026-02-01 02:28:58.145290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f963a9f687'
down_revision = '3ffe09b7cada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storeId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentonboardingstatus'), nullable=False),
    sa.Column('paymentMethod', sa.Enum('BANK_TRANSFER', 'UPI', 'PAYPAL', 'STRIPE', name='paymentmethod'), nullable=False),
    sa.Column('accountDetails', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storeId'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_onboarding_id'), 'payment_onboarding', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_onboarding_id'), table_name='payment_onboarding')
    op.drop_table('payment_onboarding')
    # ### end Alembic commands ###
