"""add store email and mobile

Revision ID: fb3f61bb854e
Revises: 86f0a7a10437
Create Date: 2025-04-30 18:37:03.558190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3f61bb854e'
down_revision = '86f0a7a10437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('email', sa.String(), nullable=False))
    op.add_column('store', sa.Column('mobile', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'store', ['mobile'])
    op.create_unique_constraint(None, 'store', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_column('store', 'mobile')
    op.drop_column('store', 'email')
    # ### end Alembic commands ###
