export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  ADMIN: '/admin',
  USER: '/user',
  DELIVERY_AGENT: '/delivery_agent',
  STORE_MANAGER: '/store_manager',
  STORE_ORDERS: '/store_manager/orders',
  PRODUCTS: '/products',
  HOME: '/',
  ORDERS: '/orders',
  PAYMENT: '/payment',
  PROFILE: '/profile',
  SIGNUP: '/signup',
  UPDATE_USER_ROLE: '/admin/update-user-role',
  CART: '/cart',
};
