name: Frontend Deployment

on:
  push:
    branches:
      - main
      - feature/deploy-actions
    # paths:
    #   - 'js/*'    # Only .js files



env:
    IAM_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}  # Replace with your IAM role ARN
    AWS_REGION: ${{ vars.AWS_REGION }}  # Replace with your AWS region

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


    #   - name: Setup Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: '18'

    #   - name: Install dependencies
    #     run: |
    #       cd js
    #       npm install

    #   - name: Build frontend
    #     run: |
    #       cd js
    #       npm run build
