name: Frontend Deployment

on:
  workflow_dispatch:
    
env:
    ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}  # Replace with your IAM role ARN
    AWS_REGION: ${{ vars.AWS_REGION }}  # Replace with your AWS region
    ECR_REPO_URL: ${{ vars.ECR_FRONTEND }} # Replace with your ECR repository URL
    TF_VAR_password: ${{ secrets.TF_VAR_PASSWORD }} 
    TF_VAR_COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.TF_VAR_COGNITO_USER_POOL_CLIENT_ID }}
    TF_VAR_COGNITO_USER_POOL_ID: ${{ secrets.TF_VAR_COGNITO_USER_POOL_ID }}
    TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_VAR_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

permissions:
  id-token: write
  contents: read
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          cd js
          npm install
          npm run build
 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./js/build



  deploy:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/terraform-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./js/build   

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image to ECR
        env:
          IMAGE_TAG: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REPO_URL }}:latest -f ./nginx/Dockerfile .
          docker tag ${{ env.ECR_REPO_URL }}:latest ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_URL }}:latest
          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_URL }}:latest

            
            
 
     