name: Frontend Deployment

on:
  push:
    branches:
      # - main
      - feature/deploy-actions
    # paths:
    #   - 'js/*'    # Only .js files

env:
    ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}  # Replace with your IAM role ARN
    AWS_REGION: ${{ vars.AWS_REGION }}  # Replace with your AWS region
    ECR_REPO_URL: ${{ vars.ECR_FRONTEND }} # Replace with your ECR repository URL
    TF_VAR_password: ${{ secrets.TF_VAR_PASSWORD }}  # Replace with your IAM role ARN

permissions:
  id-token: write
  contents: read
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          cd js
          npm install
          npm run build
 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./js/build



  deploy:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
      latest_tag: ${{ steps.set-latest-tag.outputs.image_tag_backend }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/terraform-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./js/build   

      - name: Set image tag
        id: set-image-tag
        run: |
          echo "IMAGE_TAG=v$(date -u +'%b-%d-%Y-%Hhr-%Mmin')" >> $GITHUB_OUTPUT

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image to ECR
        env:
          IMAGE_TAG: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REPO_URL }}:${{ env.IMAGE_TAG }} -f ./nginx/Dockerfile .
          docker tag ${{ env.ECR_REPO_URL }}:${{ env.IMAGE_TAG }} ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_URL }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_URL }}:${{ env.IMAGE_TAG }}

      - name: Set latest backend image tag
        id: set-latest-tag
        run: |
          LATEST_TAG=$(aws ecr describe-images --repository-name dev-indimitra-ecr \
          --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
          --output text)
          echo "Latest tag: $LATEST_TAG"
          echo "image_tag_backend=$LATEST_TAG" >> $GITHUB_OUTPUT
      
  update-ecs-task:
    needs: deploy
    uses: ./.github/workflows/update-ecs-task.yml
    with:
        image_tag_backend: ${{ needs.deploy.outputs.image_tag }} 
        image_tag_frontend: ${{ needs.deploy.outputs.latest_tag }}
    secrets: inherit
            
            
 
     