name: Test github actions

on:
    push:
        branches:
            - dev
            - main
            - feature/github-actions

# env:

#     # EC2_USER:  ${{ secrets.EC2_USER }}                  # Replace with your EC2 username
#     # EC2_HOST: ${{ secrets.EC2_HOST }}
#     # SECRET_KEY: ${{ secrets.SECRET_KEY }}
#     # MYSQL_DB: ${{ secrets.MYSQL_DB }}
#     # MYSQL_USER: ${{ secrets.MYSQL_USER }}
#     # MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#     # MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
#     # DB_ENGINE: ${{ secrets.DB_ENGINE }}
#     # DB_PORT: ${{ secrets.DB_PORT }}

jobs:
    build:
        runs-on: ubuntu-latest
        # environment: dev
        permissions:
            id-token: write  # Grant id-token permission for OIDC
            contents: read 
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Configure Aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                audience: sts.amazonaws.com
                role-to-assume: arn:aws:iam::783764611086:role/terraform-deploy
                aws-region: us-east-1




                    
            
                          
                







