name: Update ECS Task Definition

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
        ACCOUNT_ID:
            required: true
        TF_VAR_password:
            required: true

permissions:
    id-token: write
    contents: read
env:
    TF_VAR_image_tag_frontend: ${{ inputs.image_tag }}
    TF_VAR_password: ${{ secrets.TF_VAR_password }}
jobs:
  update_ecs:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/terraform-deploy
          aws-region: us-east-1

      - name: Stop current ECS task
        run: |
          cd ./terraform/
          chmod +x ecs-task-stop.sh
          ./ecs-task-stop.sh

      - name: terraform apply
        run: |
          cd ./terraform/environments/dev
          aws s3 cp s3://tf-state-indimitra/terraform.tfstate terraform.tfstate
          aws s3 cp s3://tf-state-indimitra/public-key-ssh/my-key.pub my-key.pub
          ls -la
          echo $TF_VAR_image_tag_fronted
          echo $TF_VAR_password
          terraform init 
          terraform plan
          terraform apply -auto-approve
          aws s3 cp terraform.tfstate s3://tf-state-indimitra/terraform.tfstate